---
title: Goldhirsh Foundation
timezone: America/Los_Angeles
collections:
  posts:
    title: Writing
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: /:title
permalink: pretty
